---
- name: Add user "miriyalak" to sudo
  lineinfile:
    path: /etc/sudoers.d/miriyalak
    line: 'miriyalak ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- apt: update_cache=yes

- get_url:
    url: http://engweb.eng.vmware.com/sipublic/ldap/ldap-eng-vmware.pem
    dest: /etc/ssl/certs/ldap-eng-vmware.pem

- apt:
    name:
      - ldap-auth-config
      - ldap-auth-client
      - autofs-ldap
      - nis
      - nslcd
      - libnss-ldapd
      - ldap-utils
    state: present

- apt:
    deb: http://archive.ubuntu.com/ubuntu/pool/universe/a/auth-client-config/auth-client-config_0.9ubuntu1_all.deb
