- get_url:
    url: http://apt.nicira.eng.vmware.com/apt/vmware/githooks/git-init
    dest: /usr/sbin/git-init
    mode: 0755

- git_config:
    name: core.editor
    scope: global
    value: vim

- git_config:
    name: alias.diffc
    value: diff --cached
    scope: global

- git_config:
    name: color.ui
    value: auto
    scope: global
