- git_config:
    name: core.editor
    scope: global
    value: vim

# scope=system is the default
- git_config:
    name: alias.diffc
    value: diff --cached
    scope: global

- git_config:
    name: color.ui
    value: auto
    scope: global
